---
permalink: storage-mgmt/task_monitor_metrocluster_replication.html 
sidebar: sidebar 
keywords: monitor, metrocluster, replication 
summary: 'Vous pouvez contrôler et diagnostiquer l"état de santé général des connexions logiques tout en symétrisant les données. Vous pouvez identifier les problèmes ou tout risque qui interrompt la mise en miroir des composants de cluster, tels que les agrégats, les nœuds et les machines virtuelles de stockage.' 
---
= Contrôle de la réplication MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez contrôler et diagnostiquer l'état de santé général des connexions logiques tout en symétrisant les données. Vous pouvez identifier les problèmes ou tout risque qui interrompt la mise en miroir des composants de cluster, tels que les agrégats, les nœuds et les machines virtuelles de stockage.

*Ce dont vous aurez besoin*

Le cluster local et distant en configuration MetroCluster doivent être ajoutés à Unified Manager

Vous pouvez utiliser les informations affichées sur la page Cluster / Health Details pour corriger tout problème de réplication.

Si vous déplacez le pointeur sur l'icône, vous pouvez afficher des informations détaillées sur l'événement généré.

Unified Manager utilise des alertes d'état du système pour surveiller l'état des composants et la connectivité dans la configuration MetroCluster.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Storage* > *clusters*.
+
La liste des clusters surveillés s'affiche.

. Dans la vue *Santé : tous les clusters*, cliquez sur le nom du cluster pour lequel vous souhaitez afficher les détails de la réplication MetroCluster, puis cliquez sur l'onglet *réplication MetroCluster*.
+
La topologie de la configuration MetroCluster à répliquer est affichée sur le site local, dans la zone d'objets du cluster correspondante, avec les informations relatives au site distant où les données sont mises en miroir.



Si vous détectez les problèmes de mise en miroir dans votre configuration MetroCluster, vous devez vous connecter à System Manager ou accéder à l'interface de ligne de commandes de ONTAP pour résoudre les problèmes.

*Informations connexes*

link:../health-checker/reference_health_cluster_details_page.html["Page Cluster / Health Details"]
