---
permalink: install-linux/task_download_unified_manager.html 
sidebar: sidebar 
keywords: download, Unified Manager 
summary: 'Vous devez télécharger Unified Manager `.zip` Fichier depuis le site de support NetApp pour installer Unified Manager.' 
---
= Téléchargement d'Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez télécharger Unified Manager `.zip` Fichier depuis le site de support NetApp pour installer Unified Manager.

*Ce dont vous aurez besoin*

Vous devez disposer des identifiants de connexion pour le site de support NetApp.

Vous téléchargez le même package d'installation Unified Manager pour les systèmes Red Hat Enterprise Linux et CentOS.

.Étapes
. Connectez-vous au site de support NetApp et accédez à la page de téléchargement de Unified Manager :
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de support NetApp"]

. Sélectionnez la version requise de Unified Manager et acceptez le contrat de licence utilisateur final (CLUF).
. Téléchargez le fichier d'installation Unified Manager pour Linux et enregistrez `.zip` fichier dans un répertoire du système cible.
+
[NOTE]
====
Assurez-vous de télécharger la version correcte du fichier d'installation pour votre système Red Hat Enterprise Linux. Si Red Hat Enterprise Linux 7 ou 8 est installé, assurez-vous de télécharger la version appropriée d'Unified Manager `.zip` fichier.

====
. Vérifiez la somme de contrôle pour vous assurer que le logiciel a été correctement téléchargé.

